--native development nerf
NDefines.NCountry.MIGRATORY_TRIBE_DEVELOPMENT_PROGRESS = 0.01
NDefines.NCountry.MIGRATORY_TRIBE_DEVELOPMENT_OTHER_BONUS = 0.04

--xorme tweak
--development
NDefines.NAI.DEVELOPMENT_CAP_BASE = 15
NDefines.NAI.DEVELOPMENT_CAP_MULT = 2.75
NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 0.5
--economy
NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 0.8
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 5
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 10
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = 0.1

--edict
NDefines.NAI.EDICT_VALUE_THRESHOLD = 5
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 3
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 1
NDefines.NAI.STATE_MAINTENANCE_BUDGET_FRACTION = 0.8   -- for proper edict performance. was 0.15
NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 0.8   -- for proper edict performance. was 0.1

NDefines.NAI.BUY_INDULGENCE_BASE_AI_DESIRE = 0.1
NDefines.NAI.BUY_INDULGENCE_RIVAL_AI_DESIRE = 0.2
--war & peace term 
NDefines.NAI.PEACE_TIME_LATE_FACTOR = 1.5               -- in xorme it's extreamly high (16.5) compared to original value (1.0)
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 10.0         -- in xorme it's extreamly high (100) compared to original value (3.0)
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 0.5
NDefines.NAI.PEACE_FORCE_BALANCE_FACTOR = 0.3           -- more total strength
NDefines.NAI.PEACE_MILITARY_STRENGTH_FACTOR = 7         -- less self strenth
NDefines.NAI.PEACE_WAR_DIRECTION_WINNING_MULT = 8.0     -- more reluctunt to peace when making progress
NDefines.NAI.PEACE_TERMS_CB_MULT = 2.0
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 10.0
NDefines.NAI.PEACE_TERMS_PROVINCE_WARGOAL_MULT = 8.0
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 8.0
NDefines.NAI.PEACE_TERMS_PILLAGE_CAPITAL_MULT = 2.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_ADJACENT_MULT = 0.75
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_INTEREST_MULT = 0
NDefines.NAI.PEACE_TERMS_RETURN_CORES_NOT_FRIEND_MULT = 0.1 -- was 0.75
NDefines.NAI.PEACE_TERMS_RETURN_CORES_IMPERIAL_LIBERATION_MULT = 10 -- was 2
--diplomacy
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_DISABLE_VERSUS_PLAYER_ENEMIES = 0
NDefines.NAI.DIPLOMATIC_ACTION_ENFORCE_PEACE_FORCE_BALANCE_MULT = 1.25
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_ALLY_FACTOR = 30
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_POWERBALANCE_FACTOR = 15
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_ANTI_RIVAL_FACTOR = 15
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_MONTHLY_INCOME = 8
--other
NDefines.NAI.MISSION_PICK_CHANCE = 100
NDefines.NAI.DEFENDER_OF_FAITH_BASE_AI_DESIRE = 2.5
--war
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 20.0
NDefines.NAI.TRANSPORT_FRACTION = 0.4
NDefines.NAI.BIGSHIP_FRACTION = 0.5
NDefines.NAI.AGGRESSIVENESS = 400.0
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 600.0

-- integrate the rb mod
-- Culture conversion is 50% more difficult and more costly
NDefines.NCountry.PS_CHANGE_CULTURE = 15
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 15
