NDefines.NDiplomacy.CALL_TO_ARMS_COST = 20
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_TRUST_BASE_SCORE = 30
NDefines.NAI.DIPLOMATIC_ACTION_CURRY_FAVORS_ALLIANCE_FACTOR = 16
NDefines.NDiplomacy.DECLINE_FAVOR_ACTION_STAB_HIT = 1

