NDefines.NCountry.MAX_EXTRA_PERSONALITIES = 3
NDefines.NCountry.FIRST_EXTRA_PERSONALITY = 0
NDefines.NCountry.YEARS_PER_EXTRA_PERSONALITY = 15
--
NDefines.NCountry.STARTING_ARMY_SIZE = 0.85
NDefines.NCountry.STARTING_ARMY_SIZE_AT_WAR = 1.0
NDefines.NCountry.STARTING_ARMY_SIZE_REBEL_THREAT = 0.05
NDefines.NCountry.STARTING_FLEET_SIZE = 0.95
--
NDefines.NAI.DEVELOPMENT_CAP_BASE = 30
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1.2
NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 0.4
NDefines.NAI.DANGEROUS_OVEREXTENSION_PERCENTAGE = 1.1
--
NDefines.NAI.AI_USES_HISTORICAL_IDEA_GROUPS	= 0
--
NDefines.NAI.ESTATE_MAX_PRIVILEGES = 6
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 94.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 20.0
NDefines.NAI.DANGEROUS_ESTATE_INFLUENCE_BUFFER = 6.0
--
NDefines.NAI.AGGRESSIVENESS = 625.0
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 825.0
NDefines.NAI.MISSION_PICK_CHANCE = 10000.0
NDefines.NAI.PS_SHORT_TERM_POOL = 185.0
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 1000.0
NDefines.NAI.WANT_TRIBUTARY_LOST_MANDATE = 20.0
--
NDefines.NAI.DEFENDER_OF_FAITH_BASE_AI_DESIRE = 2.245
--
NDefines.NAI.REVOLUTION_EMBRACE_MAX_ABSOLUTISM = 40
--
NDefines.NAI.EDICT_VALUE_THRESHOLD = 9
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 6
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 3
--
NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 13.0
--
NDefines.NAI.FOREIGN_MINISTER_IGNORE_DISTANCE_BASE = 7
NDefines.NAI.FOREIGN_MINISTER_BASE_PROVINCE_COUNT = 2
