NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 50.0
NDefines.NAI.MAX_SAVINGS = 425.0
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.275
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.2
NDefines.NAI.DESIRED_DEFICIT = 0.1
NDefines.NAI.DESIRED_SURPLUS = 0.115
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 3.0
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 24.0
--
NDefines.NAI.DEBASE_THRESHOLD = 700
NDefines.NAI.DRILLING_BUDGET_OF_SURPLUS = 0.75
--
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 61
NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 3
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 80.0
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 50.0
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.6
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MIN = 0.35
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MERITOCRACY_MAX = 0.8
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MERITOCRACY_MIN = 0.4
--
NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 10.0
NDefines.NAI.COLONY_BUDGET_FRACTION = 1.475
NDefines.NAI.ARMY_BUDGET_FRACTION = 6.0
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.65
NDefines.NAI.FORT_BUDGET_FRACTION = 0.85
--
NDefines.NAI.GREAT_PROJECT_DESIRE_MOVE_FROM_SUBJECT_MODIFIER = 3.5
NDefines.NAI.GREAT_PROJECT_DESIRE_LEAVE_IN_SUBJECT_MODIFIER = 0.5
NDefines.NAI.GREAT_PROJECT_DESIRE_UPGRADE_IN_SUBJECT_MODIFIER = 0.5
NDefines.NAI.GREAT_PROJECT_DESIRE_UPGRADE_MODIFIER = 5.5
NDefines.NAI.GREAT_PROJECT_DESIRE_BUILD_NEW_MODIFIER = 5.0
NDefines.NAI.GREAT_PROJECT_DESIRE_CAPITAL_MODIFIER = 5.0
NDefines.NAI.GREAT_PROJECT_DESIRE_CAPITAL_BASE = 100.0
NDefines.NAI.GREAT_PROJECT_DESIRE_CAPITAL_AREA_MODIFIER = 5.0
--
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 10000.0
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 10000.0
--
NDefines.NAI.UPGRADE_CENTER_OF_TRADE_BASE_AI_DESIRE = 500.0
--
NDefines.NAI.AI_FORT_PER_DEV_RATIO = 36
NDefines.NAI.FORT_ON_BORDER_MULT = 1.79
NDefines.NAI.FORT_NEXT_TO_FORT_MULT = 0.01
--
NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 2.0
NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.11
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 2.85
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 3.0
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 4.5
NDefines.NAIEconomy.MISSIONARY_FRACTION = 0.175
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 2.1
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 4.35
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 2.2
NDefines.NAIEconomy.NAVY_FRACTION_PEACEFUL = 2.0
NDefines.NAIEconomy.NAVY_FRACTION_CAPITALIST = 2.0
NDefines.NAIEconomy.FORT_FRACTION_MILITARIZE = 4.0
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 7.0
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 6.0
NDefines.NAIEconomy.REBEL_THREAT_MILITARIZE_THRESHOLD = 1.0